# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Srinidhi Hegde
name: Srinidhi Hegde
position: Graduate Researcher 
organization: "University of Maryland College Park"
email: srihegde@umd.edu
description: >-
  I am a research assistant at [UMIACS](https://www.umiacs.umd.edu/) working with [Prof. Matthias Zwicker](https://www.cs.umd.edu/~zwicker/) on efficient neural rendering solutions for point cloud visualization. My broader research interests lie at the intersection of 3D Vision and Computer Graphics with applications to mixed reality (AR/VR/XR) and scientific visualization. I previously worked at [TCS Research](https://www.tcs.com/what-we-do/research) with [Dr. Lovekesh Vig](https://sites.google.com/site/lovekeshhome/) and [Ms. Ramya Hebbalaguppe](https://rhebbalaguppe.github.io) on designing deep learning solutions for AR. I completed my undergraduate study in Computer Science and Engineering at [IIITD](https://iiitd.ac.in/) where I collaborated with [Prof. Saket Anand](http://faculty.iiitd.ac.in/~anands/) and [Prof. Ojaswa Sharma](http://faculty.iiitd.ac.in/~ojaswa/) on scene reconstruction and procedural modeling.
  <br>
  <br>

  **[CV](/resources/Srinidhi_Hegde_CV.pdf) (as of Sep-2024).**
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srihegde.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 
resume: 

# Navbar items
navbar_items:
  - name: Home
    url: /
  - name: Projects
    url: /pages/projects.html
  # - name: Misc
  #   url: /misc/

# Social media links
social:
  - title: "Github"
    url: "https://github.com/srihegde"
    icon: "fab fa-github"
  - title: "Linkedin"
    url: "https://www.linkedin.com/in/srihegde/"
    icon: "fab fa-linkedin"
  - title: "Twitter"
    url: "https://x.com/_srihegde_"
    icon: "fa-brands fa-x-twitter"
  - title: "Google Scholar"
    url: "https://scholar.google.co.in/citations?user=yRIA06YAAAAJ&hl=en"
    icon: "ai ai-google-scholar"
  - title: "Email"
    url: "mailto:srihegde@umd.edu"
    icon: "fa fa-envelope"

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Description drafts
# <!-- **Welcome to my academic homepage!** -->
# <!-- I am a graduate researcher at the University of Maryland, College Park.  -->
# <br>
# and [Prof. Jia-bin Huang](https://jbhuang0604.github.io/) on photo-geometric factors in 2D generative models